name: CI

on:
  pull_request:
  push:
    branches:
      - master
      - develop

jobs:
  build-test:
    strategy:
      matrix:
        os: ["ubuntu-22.04", "macos-12", "windows-2022"]
        protoc-version: ["21.x", "23.x"]
        python-version: ["3.8", "3.11"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Install Protoc
      uses: arduino/setup-protoc@v2
      with:
        version: ${{ matrix.protoc-version }}
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install gcovr
      run: pip install gcovr==5.2
    - name: Setup venv
      run: python setup.py
    - name: Build test
      run: ./test/scripts/build_test.py
    - name: Code coverage
      run: ./test/scripts/code_coverage.py
